In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
a.dtype

dtype('int64')

In [6]:
#knowing the dimensions of the array
a.ndim

1

In [7]:
#array length
a.size

3

In [9]:
#the attribute strength
a.shape

(3,)

In [10]:
b = np.array([[1.3,2.4],[0.3,4.1]])

In [11]:
b.dtype

dtype('float64')

In [12]:
#the dimensions of the array
b.ndim

2

In [13]:
b.size

4

In [14]:
b.shape

(2, 2)

In [15]:
#getting the byte size
b.itemsize

8

In [16]:
#numpy arrays can accept lists and tuples
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d = np.array(((1,2,3),(4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#A numpy array can accept both lists and tuples
e = np.array([(1,2,3),[4,5,6],(7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Now playing with strings
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [20]:
g.dtype

dtype('<U1')

In [21]:
g.dtype.name

'str32'

In [22]:
#incorporate complex numbers
f = np.array([[1,2,3],[4,5,6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#using he arange function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [28]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [29]:
#Putting a list of numbers in a list
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
#the third argument determines the amount of numbers in the output
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.random.random(3)

array([0.76392346, 0.23219346, 0.12390928])

In [33]:
#Basic Operations
a = np.arange(4)
a

array([0, 1, 2, 3])

In [34]:
a + 4

array([4, 5, 6, 7])

In [35]:
a*2

array([0, 2, 4, 6])

In [36]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [37]:
a + b

array([ 4,  6,  8, 10])

In [38]:
a - b

array([-4, -4, -4, -4])

In [39]:
a * b

array([ 0,  5, 12, 21])

In [41]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [42]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [43]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
 A + B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [46]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [47]:
#Now using the dot product
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [48]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [49]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [50]:
#Increment and Decrement Operators
a = np.arange(4)
a

array([0, 1, 2, 3])

In [52]:
a +=1
a

array([2, 3, 4, 5])

In [53]:
a-= 1
a

array([1, 2, 3, 4])

In [54]:
a += 4
a

array([5, 6, 7, 8])

In [56]:
a *= 2
a

array([20, 24, 28, 32])

In [57]:
#Aggregate Function
a = np.array([3.3,4.5,1.2,5.7,0.3])

In [58]:
a.sum()

15.0

In [59]:
a.min()

0.3

In [60]:
a.max()

5.7

In [61]:
a.mean()

3.0

In [62]:
a.std()

2.0079840636817816

In [63]:
#Indexing
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [64]:
a[4]

14

In [65]:
a[-1]

15

In [66]:
a[-6]

10

In [67]:
a[[1,3,4]]

array([11, 13, 14])

In [68]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [69]:
A[1,2]

15

In [70]:
#Sliciing
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [71]:
a[1:5]

array([11, 12, 13, 14])

In [72]:
a[1:5:2]

array([11, 13])

In [73]:
a[::2]

array([10, 12, 14])

In [74]:
a[:5:2]

array([10, 12, 14])

In [75]:
a[:5:]

array([10, 11, 12, 13, 14])

In [76]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [77]:
A[0,:]

array([10, 11, 12])

In [78]:
#extract the first number in each array
A[:,0]

array([10, 13, 16])

In [81]:
#extract the first and second number in the first two arrays
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [82]:
#iterating an array
for i in a:
    print(i)

10
11
12
13
14
15


In [83]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [84]:
#if you want to print the numbers in an array individually 
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [85]:
#Conditions and Boolean Arrays
A = np.random.random((4,4))
A

array([[0.6894814 , 0.60907109, 0.56613613, 0.14183684],
       [0.39401651, 0.3129428 , 0.81955561, 0.88974081],
       [0.82218717, 0.81999683, 0.27607521, 0.86996697],
       [0.42945079, 0.72067716, 0.9919589 , 0.8221853 ]])

In [86]:
A < 0.5

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [87]:
#Prints the values that are true
A[A < 0.5]

array([0.14183684, 0.39401651, 0.3129428 , 0.27607521, 0.42945079])

In [88]:
#shape Manipulation
a = np.random.random(12)
a

array([0.71689048, 0.72334935, 0.42849419, 0.47840585, 0.83669249,
       0.98611276, 0.10976981, 0.88125498, 0.79761138, 0.41220232,
       0.60600643, 0.49257764])

In [90]:
A = a.reshape(3,4)
A

array([[0.71689048, 0.72334935, 0.42849419, 0.47840585],
       [0.83669249, 0.98611276, 0.10976981, 0.88125498],
       [0.79761138, 0.41220232, 0.60600643, 0.49257764]])

In [91]:
#if you want to alter its shape
a.shape = (4,3)
a

array([[0.71689048, 0.72334935, 0.42849419],
       [0.47840585, 0.83669249, 0.98611276],
       [0.10976981, 0.88125498, 0.79761138],
       [0.41220232, 0.60600643, 0.49257764]])

In [93]:
#to convert everything into a 1d array
a = a.ravel()
a

array([0.71689048, 0.72334935, 0.42849419, 0.47840585, 0.83669249,
       0.98611276, 0.10976981, 0.88125498, 0.79761138, 0.41220232,
       0.60600643, 0.49257764])

In [95]:
#Array Manipulation
#Joining Arrays vetically
A = np.ones((3,3))
B = np.zeros((3,3))
#np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
#Joining arrays horzontally
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [97]:
#this time with 3 numpy arrays
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [98]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [100]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
#Split Arrays
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
#Horizontal Split
[B,C] = np.hsplit(A,2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [106]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [107]:
#Vertical Split
[B,C] = np.vsplit(A,2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [108]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
#Something more complex
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [110]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [111]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [112]:
#NOW do it by row
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [113]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
A3

array([[12, 13, 14, 15]])

In [115]:
#Copies or Views Objects
a = np.array([1,2,3,4])
b= a
b

array([1, 2, 3, 4])

In [116]:
a[2] = 0
b

array([1, 2, 0, 4])

In [117]:
c = a[0:2]
c

array([1, 2])

In [118]:
a[0] = 0
c

array([0, 2])

In [119]:
a = np.array([1,2,3,4])
c = a.copy()
c

array([1, 2, 3, 4])

In [120]:
a[0]= 0
c

array([1, 2, 3, 4])

In [1]:
import pandas as pd

In [2]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [2]:
#Creating a series with an index
s = pd.Series([12,-4,7,9], index= ['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

In [3]:
#looking at the values in the Series
s.values

array([12, -4,  7,  9])

In [4]:
#Looking at the indexes in the Series
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
#Selecting certain elements
s[2]

7

In [6]:
s['b']

-4

In [7]:
s[0:2]

a    12
b    -4
dtype: int64

In [8]:
#Assigning Values to the Elements
s[1]= 0
s

a    12
b     0
c     7
d     9
dtype: int64

In [9]:
s['b'] = 1
s

a    12
b     1
c     7
d     9
dtype: int64

In [10]:
#Defining a Series from NumPy Arrays and Other Series
import numpy as np
arr = np.array([1,2,3,4])
s3 = pd.Series(arr)
s3

0    1
1    2
2    3
3    4
dtype: int64

In [11]:
s4 = pd.Series(s)
s4

a    12
b     1
c     7
d     9
dtype: int64

In [12]:
arr[2] = -2
s3

0    1
1    2
2   -2
3    4
dtype: int64

In [13]:
#Filtering Values
s[s >8]

a    12
d     9
dtype: int64

In [14]:
#Operations and Mathematical Functions
s / 2

a    6.0
b    0.5
c    3.5
d    4.5
dtype: float64

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.log(s)

NameError: name 's' is not defined

In [ ]:
serd = pd.Series([1,0,2,1,2,3], index = ['white','white','blue','green','green','yellow'])
serd

In [ ]:
serd.unique()

In [ ]:
serd.value_counts()

In [ ]:
serd.isin(([0,3]))

In [3]:
serd.isin([0,3])

NameError: name 'serd' is not defined

In [4]:
s2= pd.Series([5, -3, np.NaN,14])
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [5]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [7]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

In [8]:
s2[s2.isnull()]

2   NaN
dtype: float64

In [9]:
#Series as Dictionaries
mydict = {'red':200, 'blue': 1000, 'yellow': 500, 'orange': 1000}

In [10]:
myseries = pd.Series(mydict)
myseries

red        200
blue      1000
yellow     500
orange    1000
dtype: int64

In [11]:
colors = ['red','yellow','orange','blue','green']
myseries = pd.Series(mydict, index =colors)
myseries

red        200.0
yellow     500.0
orange    1000.0
blue      1000.0
green        NaN
dtype: float64

In [12]:
#Defining a dataframe
data = {'color': ['blue','green','yellow','red','white'],
       'object' : ['ball','pen','pencil','paper','mug'],
       'price': [1.2,1.0,0.6,0.9,1.7]}
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [13]:
frame2 = pd.DataFrame(data, columns = ['object','price'])
frame2

object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [14]:
frame3 = pd.DataFrame(np.arange(16).reshape((4,4)),
                     index =['red','blue','yellow','white'],
                     columns=['ball','pen','pencil','paper'])
frame3

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [15]:
#Selecting elements
frame.columns

Index(['color', 'object', 'price'], dtype='object')

In [16]:
frame.values

array([['blue', 'ball', 1.2],
       ['green', 'pen', 1.0],
       ['yellow', 'pencil', 0.6],
       ['red', 'paper', 0.9],
       ['white', 'mug', 1.7]], dtype=object)

In [17]:
frame['price']

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [18]:
frame.price

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [19]:
frame.loc[2]

color     yellow
object    pencil
price        0.6
Name: 2, dtype: object

In [20]:
frame.loc[[2,4]]

color  object  price
2  yellow  pencil    0.6
4   white     mug    1.7

In [21]:
frame[1:3]

color  object  price
1   green     pen    1.0
2  yellow  pencil    0.6

In [22]:
frame['object'][3]

'paper'

In [1]:
import pandas as pd
import numpy as np

In [2]:
ser = pd.Series([5,0,3,8,4], index = ['red','blue','yellow','white','green'])
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [3]:
ser.sort_index()

blue      0
green     4
red       5
white     8
yellow    3
dtype: int64

In [4]:
ser.sort_index(ascending=False)

yellow    3
white     8
red       5
green     4
blue      0
dtype: int64

In [5]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)), index=['red','blue','yellow','white'],columns=['ball','pen','pencil','paper'])
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [6]:
frame.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [7]:
frame.sort_index(axis=1)

ball  paper  pen  pencil
red        0      3    1       2
blue       4      7    5       6
yellow     8     11    9      10
white     12     15   13      14

In [8]:
ser.sort_values()

blue      0
yellow    3
green     4
red       5
white     8
dtype: int64

In [10]:
#sorting values of a particular column
frame.sort_values(by='pen')

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [11]:
#same as above but with 2 columns
frame.sort_values(by=['pen','pencil'])

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [12]:
ser.rank()

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

In [13]:
ser.rank(method='first')

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

In [14]:
ser.rank(ascending = False)

red       2.0
blue      5.0
yellow    4.0
white     1.0
green     3.0
dtype: float64

In [1]:
 #Chapter 6 Pandas in Depth: Data Manipulation

In [1]:
#Merging
import numpy as np
import pandas as pd

In [2]:
frame1 = pd.DataFrame({'id':['ball','pencil','pen','mug','ashtray'], 'price': [12.33, 11.44, 33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [3]:
frame2 = pd.DataFrame({'id':['pencil','pencil','ball','pen'], 'color':['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [4]:
#merging both dataframes
pd.merge(frame1, frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [5]:
#now trying two merge two dataframes with different number of columns
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'], 'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [6]:
frame2 = pd.DataFrame( { 'id':['pencil','pencil','ball','pen'], 'brand':['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [7]:
#the merge results are empty because there are two data frames that show the same a column name
#in order to fix this you need a column to join on
pd.merge(frame1,frame2, on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [8]:
#now performing a merge on the brand column
pd.merge(frame1, frame2, on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [9]:
#change the column names
frame2.columns = ['brand','sid']
frame2

brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [10]:
frame2.columns= ['brand', 'id']
pd.merge(frame1,frame2, on='id')

Empty DataFrame
Columns: [id, color, brand_x, brand_y]
Index: []

In [11]:
#similar to an outer join
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN
5      OMG    NaN     NaN  pencil
6      POD    NaN     NaN  pencil
7      POD    NaN     NaN     pen
8      ABC    NaN     NaN    ball

In [12]:
#similar to a left join
pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN

In [13]:
#similar to a right join
pd.merge(frame1,frame2,on='id',how='right')

id color brand_x brand_y
0  OMG   NaN     NaN  pencil
1  POD   NaN     NaN  pencil
2  POD   NaN     NaN     pen
3  ABC   NaN     NaN    ball

In [14]:
#perform multiple joins
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

id  color   brand
0     ball  white     OMG
1   pencil    red     ABC
2      pen    red     ABC
3      mug  black     POD
4  ashtray  green     POD
5      OMG    NaN  pencil
6      POD    NaN  pencil
7      ABC    NaN    ball
8      POD    NaN     pen

In [15]:
#Concatenating Section
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
#Concatenating both arrays
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [18]:
#A variation 
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
#concatenating with pandas Series
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.794347
2    0.161064
3    0.288216
4    0.856943
dtype: float64

In [20]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.048437
6    0.391311
7    0.755414
8    0.400838
dtype: float64

In [21]:
pd.concat([ser1,ser2])

1    0.794347
2    0.161064
3    0.288216
4    0.856943
5    0.048437
6    0.391311
7    0.755414
8    0.400838
dtype: float64

In [22]:
#including an axis
pd.concat([ser1,ser2], axis=1)

0         1
1  0.794347       NaN
2  0.161064       NaN
3  0.288216       NaN
4  0.856943       NaN
5       NaN  0.048437
6       NaN  0.391311
7       NaN  0.755414
8       NaN  0.400838

In [23]:
#adding a heirarchial key
pd.concat([ser1,ser2],keys=[1,2])

1  1    0.794347
   2    0.161064
   3    0.288216
   4    0.856943
2  5    0.048437
   6    0.391311
   7    0.755414
   8    0.400838
dtype: float64

In [24]:
pd.concat([ser1,ser2],axis=1,keys=[1,2])

1         2
1  0.794347       NaN
2  0.161064       NaN
3  0.288216       NaN
4  0.856943       NaN
5       NaN  0.048437
6       NaN  0.391311
7       NaN  0.755414
8       NaN  0.400838

In [25]:
#Now trying it with dataframes
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], columns=['A','B','C'])

In [26]:
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], columns=['A','B','C'])

In [27]:
pd.concat([frame1,frame2])

A         B         C
1  0.776065  0.765457  0.616673
2  0.091820  0.878899  0.853259
3  0.377411  0.069392  0.421362
4  0.891479  0.536719  0.312775
5  0.174676  0.998918  0.971878
6  0.644373  0.617283  0.875201

In [28]:
#Pivoting
frame1 = pd.DataFrame(np.arange(9).reshape(3,3), index=['white','black','red'], columns = ['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [29]:
#stacking
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int64

In [30]:
#unstacking
ser5.unstack()

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [31]:
#removing
frame1 = pd.DataFrame(np.arange(9).reshape(3,3), index=['white','black','red'], columns = ['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [32]:
#removing a column
del frame1['ball']
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [33]:
#removing a row
frame1.drop('white')

pen  pencil
black    4       5
red      7       8

In [34]:
#Removing Duplicates
dframe = pd.DataFrame({'color':['white','white','red','red','white'], 'value':[2,1,3,3,2]})
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [35]:
#determines whether or not the value is duplicated
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [36]:
#Looking at how many rows that have duplicated values
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [37]:
#Mapping Section

In [38]:
#Replacing values via mapping
frame = pd.DataFrame({'item':['ball','mug','pen','pencil','ashtray'],
                     'color':['white','rosso','verde','black','yellow'],
                     'price':[5.56,4.20,1.30,0.56,2.75]})
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [39]:
#replacing color names
newcolors = {
    'rosso':'red',
    'verde':'green'
}

In [40]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [42]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [43]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

In [44]:
#Adding values via mapping
frame = pd.DataFrame({'item':['ball','mug','pen','pencil','ashtray'],
                     'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [45]:
prices = {
    'ball': 5.56,
    'mug': 4.20,
    'bottle': 1.30,
    'scissors': 0.56,
    'pen': 1.30,
    'pencil':0.56,
    'astray': 2.75
}

In [46]:
frame['price'] = frame['item'].map(prices)
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow    NaN

In [47]:
#rename the indexes of the axes
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow    NaN

In [48]:
reindex = {
    0: 'first',
    1: 'second',
    2: 'third',
    3: 'fourth',
    4: 'fifth'
}

In [49]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow    NaN

In [50]:
recolumn = {
    'item':'object',
    'price':'value'
}

In [51]:
frame.rename(index=reindex,columns = recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow    NaN

In [52]:
frame.rename(index={1:'first'},columns={'item':'object'})

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow    NaN

In [53]:
frame.rename(columns={'item':'object'},inplace=True)
frame

object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow    NaN

In [54]:
#Discretization and Binning
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
bins = [0,25,50,75,100]

In [55]:
cat = pd.cut(results,bins)

In [56]:
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [57]:
cat.categories

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]],
              closed='right',
              dtype='interval[int64]')

In [58]:
cat.codes

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3], dtype=int8)

In [60]:
pd.value_counts(cat)

(75, 100]    5
(50, 75]     4
(25, 50]     4
(0, 25]      4
dtype: int64

In [61]:
bin_names = ['unlikely','less likely','likely','highly likely']
pd.cut(results,bins, labels=bin_names)

[unlikely, less likely, likely, likely, less likely, ..., highly likely, unlikely, less likely, highly likely, highly likely]
Length: 17
Categories (4, object): [unlikely < less likely < likely < highly likely]

In [62]:
pd.cut(results,5)

[(2.904, 22.2], (22.2, 41.4], (60.6, 79.8], (41.4, 60.6], (22.2, 41.4], ..., (79.8, 99.0], (22.2, 41.4], (41.4, 60.6], (79.8, 99.0], (79.8, 99.0]]
Length: 17
Categories (5, interval[float64]): [(2.904, 22.2] < (22.2, 41.4] < (41.4, 60.6] < (60.6, 79.8] < (79.8, 99.0]]

In [64]:
quintiles = pd.qcut(results,5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] < (62.6, 87.0] < (87.0, 99.0]]

In [65]:
pd.value_counts(quintiles)

(62.6, 87.0]     4
(2.999, 24.0]    4
(87.0, 99.0]     3
(46.0, 62.6]     3
(24.0, 46.0]     3
dtype: int64

In [66]:
#Detecting and Filtering Outliers

In [67]:
randframe = pd.DataFrame(np.random.randn(1000,3))

In [68]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean      0.078074     0.009975    -0.028566
std       0.987990     1.031360     0.994223
min      -3.148404    -3.817634    -2.729299
25%      -0.589610    -0.666745    -0.711019
50%       0.099008     0.022395    -0.005179
75%       0.725047     0.735821     0.605251
max       3.075985     3.461654     3.775239

In [69]:
randframe.std()

0    0.987990
1    1.031360
2    0.994223
dtype: float64

In [70]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)]

0         1         2
330 -0.285364 -3.817634  0.758855
364 -0.144582  3.461654 -0.542775
395  3.075985  1.716098  1.021032
428  3.066368  0.988165 -2.025779
431 -3.148404 -1.004649  0.757496
442  1.048308 -0.180386  3.159566
499 -3.090500  0.028742  0.111571
568  0.880309 -3.122735  0.724296
636 -0.050642 -0.617977  3.775239
760 -0.573131 -0.792016  3.224710

In [72]:
#Permutation
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [74]:
new_order = np.random.permutation(5)
new_order

array([1, 0, 4, 2, 3])

In [75]:
nframe.take(new_order)

0   1   2   3   4
1   5   6   7   8   9
0   0   1   2   3   4
4  20  21  22  23  24
2  10  11  12  13  14
3  15  16  17  18  19

In [76]:
new_order = [3,4,2]
nframe.take(new_order)

0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24
2  10  11  12  13  14

In [77]:
#Random Sampling

In [78]:
sample = np.random.randint(0,len(nframe),size=3)
sample

array([2, 4, 0])

In [79]:
#String Manipulation Section

In [80]:
text = '16 Bolton Avenue, Boston'
text.split(',')

['16 Bolton Avenue', ' Boston']

In [81]:
tokens = [s.strip() for s in text.split(',')]
tokens

['16 Bolton Avenue', 'Boston']

In [83]:
address, city = [s.strip() for s in text.split(',')]
address
city

'Boston'

In [84]:
address + ',' + city

'16 Bolton Avenue,Boston'

In [85]:
strings = ['A+','A','A-','B','BB','BBB','C+']
';'.join(strings)

'A+;A;A-;B;BB;BBB;C+'

In [86]:
#Data Aggregations

In [88]:
frame = pd.DataFrame({'color': ['white','red','green','red','green'],
                     'object': ['pen','pencil','pencil','ashtray','pen'],
                     'price1': [5.56,4.20,1.30,0.56,2.75],
                     'price2': [4.75,4.12,1.60,0.75,3.15]})
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [89]:
#performing a groupby
group = frame['price1'].groupby(frame['color'])
group

In [90]:
group.groups

{'green': Int64Index([2, 4], dtype='int64'),
 'red': Int64Index([1, 3], dtype='int64'),
 'white': Int64Index([0], dtype='int64')}

In [91]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [92]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

In [93]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])
ggroup.groups

{('green', 'pen'): Int64Index([4], dtype='int64'),
 ('green', 'pencil'): Int64Index([2], dtype='int64'),
 ('red', 'ashtray'): Int64Index([3], dtype='int64'),
 ('red', 'pencil'): Int64Index([1], dtype='int64'),
 ('white', 'pen'): Int64Index([0], dtype='int64')}

In [94]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [95]:
frame[['price1','price2']].groupby(frame['color']).mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [96]:
#group iteration 
for name, group in frame.groupby('color'):
    print(name)
    print(group)

green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


In [97]:
#continue on page 222