In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
a.dtype

dtype('int64')

In [6]:
#knowing the dimensions of the array
a.ndim

1

In [7]:
#array length
a.size

3

In [9]:
#the attribute strength
a.shape

(3,)

In [10]:
b = np.array([[1.3,2.4],[0.3,4.1]])

In [11]:
b.dtype

dtype('float64')

In [12]:
#the dimensions of the array
b.ndim

2

In [13]:
b.size

4

In [14]:
b.shape

(2, 2)

In [15]:
#getting the byte size
b.itemsize

8

In [16]:
#numpy arrays can accept lists and tuples
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d = np.array(((1,2,3),(4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#A numpy array can accept both lists and tuples
e = np.array([(1,2,3),[4,5,6],(7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Now playing with strings
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [20]:
g.dtype

dtype('<U1')

In [21]:
g.dtype.name

'str32'

In [22]:
#incorporate complex numbers
f = np.array([[1,2,3],[4,5,6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#using he arange function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [28]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [29]:
#Putting a list of numbers in a list
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
#the third argument determines the amount of numbers in the output
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.random.random(3)

array([0.76392346, 0.23219346, 0.12390928])

In [33]:
#Basic Operations
a = np.arange(4)
a

array([0, 1, 2, 3])

In [34]:
a + 4

array([4, 5, 6, 7])

In [35]:
a*2

array([0, 2, 4, 6])

In [36]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [37]:
a + b

array([ 4,  6,  8, 10])

In [38]:
a - b

array([-4, -4, -4, -4])

In [39]:
a * b

array([ 0,  5, 12, 21])

In [41]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [42]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [43]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
 A + B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [46]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [47]:
#Now using the dot product
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [48]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [49]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [50]:
#Increment and Decrement Operators
a = np.arange(4)
a

array([0, 1, 2, 3])

In [52]:
a +=1
a

array([2, 3, 4, 5])

In [53]:
a-= 1
a

array([1, 2, 3, 4])

In [54]:
a += 4
a

array([5, 6, 7, 8])

In [56]:
a *= 2
a

array([20, 24, 28, 32])

In [57]:
#Aggregate Function
a = np.array([3.3,4.5,1.2,5.7,0.3])

In [58]:
a.sum()

15.0

In [59]:
a.min()

0.3

In [60]:
a.max()

5.7

In [61]:
a.mean()

3.0

In [62]:
a.std()

2.0079840636817816

In [63]:
#Indexing
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [64]:
a[4]

14

In [65]:
a[-1]

15

In [66]:
a[-6]

10

In [67]:
a[[1,3,4]]

array([11, 13, 14])

In [68]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [69]:
A[1,2]

15

In [70]:
#Sliciing
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [71]:
a[1:5]

array([11, 12, 13, 14])

In [72]:
a[1:5:2]

array([11, 13])

In [73]:
a[::2]

array([10, 12, 14])

In [74]:
a[:5:2]

array([10, 12, 14])

In [75]:
a[:5:]

array([10, 11, 12, 13, 14])

In [76]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [77]:
A[0,:]

array([10, 11, 12])

In [78]:
#extract the first number in each array
A[:,0]

array([10, 13, 16])

In [81]:
#extract the first and second number in the first two arrays
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [82]:
#iterating an array
for i in a:
    print(i)

10
11
12
13
14
15


In [83]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [84]:
#if you want to print the numbers in an array individually 
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [85]:
#Conditions and Boolean Arrays
A = np.random.random((4,4))
A

array([[0.6894814 , 0.60907109, 0.56613613, 0.14183684],
       [0.39401651, 0.3129428 , 0.81955561, 0.88974081],
       [0.82218717, 0.81999683, 0.27607521, 0.86996697],
       [0.42945079, 0.72067716, 0.9919589 , 0.8221853 ]])

In [86]:
A < 0.5

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [87]:
#Prints the values that are true
A[A < 0.5]

array([0.14183684, 0.39401651, 0.3129428 , 0.27607521, 0.42945079])

In [88]:
#shape Manipulation
a = np.random.random(12)
a

array([0.71689048, 0.72334935, 0.42849419, 0.47840585, 0.83669249,
       0.98611276, 0.10976981, 0.88125498, 0.79761138, 0.41220232,
       0.60600643, 0.49257764])

In [90]:
A = a.reshape(3,4)
A

array([[0.71689048, 0.72334935, 0.42849419, 0.47840585],
       [0.83669249, 0.98611276, 0.10976981, 0.88125498],
       [0.79761138, 0.41220232, 0.60600643, 0.49257764]])

In [91]:
#if you want to alter its shape
a.shape = (4,3)
a

array([[0.71689048, 0.72334935, 0.42849419],
       [0.47840585, 0.83669249, 0.98611276],
       [0.10976981, 0.88125498, 0.79761138],
       [0.41220232, 0.60600643, 0.49257764]])

In [93]:
#to convert everything into a 1d array
a = a.ravel()
a

array([0.71689048, 0.72334935, 0.42849419, 0.47840585, 0.83669249,
       0.98611276, 0.10976981, 0.88125498, 0.79761138, 0.41220232,
       0.60600643, 0.49257764])

In [95]:
#Array Manipulation
#Joining Arrays vetically
A = np.ones((3,3))
B = np.zeros((3,3))
#np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
#Joining arrays horzontally
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [97]:
#this time with 3 numpy arrays
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [98]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [100]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
#Split Arrays
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
#Horizontal Split
[B,C] = np.hsplit(A,2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [106]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [107]:
#Vertical Split
[B,C] = np.vsplit(A,2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [108]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
#Something more complex
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [110]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [111]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [112]:
#NOW do it by row
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [113]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
A3

array([[12, 13, 14, 15]])

In [115]:
#Copies or Views Objects
a = np.array([1,2,3,4])
b= a
b

array([1, 2, 3, 4])

In [116]:
a[2] = 0
b

array([1, 2, 0, 4])

In [117]:
c = a[0:2]
c

array([1, 2])

In [118]:
a[0] = 0
c

array([0, 2])

In [119]:
a = np.array([1,2,3,4])
c = a.copy()
c

array([1, 2, 3, 4])

In [120]:
a[0]= 0
c

array([1, 2, 3, 4])

In [1]:
import pandas as pd

In [2]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [2]:
#Creating a series with an index
s = pd.Series([12,-4,7,9], index= ['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

In [3]:
#looking at the values in the Series
s.values

array([12, -4,  7,  9])

In [4]:
#Looking at the indexes in the Series
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
#Selecting certain elements
s[2]

7

In [6]:
s['b']

-4

In [7]:
s[0:2]

a    12
b    -4
dtype: int64

In [8]:
#Assigning Values to the Elements
s[1]= 0
s

a    12
b     0
c     7
d     9
dtype: int64

In [9]:
s['b'] = 1
s

a    12
b     1
c     7
d     9
dtype: int64

In [10]:
#Defining a Series from NumPy Arrays and Other Series
import numpy as np
arr = np.array([1,2,3,4])
s3 = pd.Series(arr)
s3

0    1
1    2
2    3
3    4
dtype: int64

In [11]:
s4 = pd.Series(s)
s4

a    12
b     1
c     7
d     9
dtype: int64

In [12]:
arr[2] = -2
s3

0    1
1    2
2   -2
3    4
dtype: int64

In [13]:
#Filtering Values
s[s >8]

a    12
d     9
dtype: int64

In [14]:
#Operations and Mathematical Functions
s / 2

a    6.0
b    0.5
c    3.5
d    4.5
dtype: float64

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.log(s)

NameError: name 's' is not defined

In [ ]:
serd = pd.Series([1,0,2,1,2,3], index = ['white','white','blue','green','green','yellow'])
serd

In [ ]:
serd.unique()

In [ ]:
serd.value_counts()

In [ ]:
serd.isin(([0,3]))

In [3]:
serd.isin([0,3])

NameError: name 'serd' is not defined

In [4]:
s2= pd.Series([5, -3, np.NaN,14])
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [5]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [7]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

In [8]:
s2[s2.isnull()]

2   NaN
dtype: float64

In [9]:
#Series as Dictionaries
mydict = {'red':200, 'blue': 1000, 'yellow': 500, 'orange': 1000}

In [10]:
myseries = pd.Series(mydict)
myseries

red        200
blue      1000
yellow     500
orange    1000
dtype: int64

In [11]:
colors = ['red','yellow','orange','blue','green']
myseries = pd.Series(mydict, index =colors)
myseries

red        200.0
yellow     500.0
orange    1000.0
blue      1000.0
green        NaN
dtype: float64

In [12]:
#Defining a dataframe
data = {'color': ['blue','green','yellow','red','white'],
       'object' : ['ball','pen','pencil','paper','mug'],
       'price': [1.2,1.0,0.6,0.9,1.7]}
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [13]:
frame2 = pd.DataFrame(data, columns = ['object','price'])
frame2

object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [14]:
frame3 = pd.DataFrame(np.arange(16).reshape((4,4)),
                     index =['red','blue','yellow','white'],
                     columns=['ball','pen','pencil','paper'])
frame3

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [15]:
#Selecting elements
frame.columns

Index(['color', 'object', 'price'], dtype='object')

In [16]:
frame.values

array([['blue', 'ball', 1.2],
       ['green', 'pen', 1.0],
       ['yellow', 'pencil', 0.6],
       ['red', 'paper', 0.9],
       ['white', 'mug', 1.7]], dtype=object)

In [17]:
frame['price']

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [18]:
frame.price

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [19]:
frame.loc[2]

color     yellow
object    pencil
price        0.6
Name: 2, dtype: object

In [20]:
frame.loc[[2,4]]

color  object  price
2  yellow  pencil    0.6
4   white     mug    1.7

In [21]:
frame[1:3]

color  object  price
1   green     pen    1.0
2  yellow  pencil    0.6

In [22]:
frame['object'][3]

'paper'

In [1]:
import pandas as pd
import numpy as np

In [2]:
ser = pd.Series([5,0,3,8,4], index = ['red','blue','yellow','white','green'])
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [3]:
ser.sort_index()

blue      0
green     4
red       5
white     8
yellow    3
dtype: int64

In [4]:
ser.sort_index(ascending=False)

yellow    3
white     8
red       5
green     4
blue      0
dtype: int64

In [5]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)), index=['red','blue','yellow','white'],columns=['ball','pen','pencil','paper'])
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [6]:
frame.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [7]:
frame.sort_index(axis=1)

ball  paper  pen  pencil
red        0      3    1       2
blue       4      7    5       6
yellow     8     11    9      10
white     12     15   13      14

In [8]:
ser.sort_values()

blue      0
yellow    3
green     4
red       5
white     8
dtype: int64

In [10]:
#sorting values of a particular column
frame.sort_values(by='pen')

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [11]:
#same as above but with 2 columns
frame.sort_values(by=['pen','pencil'])

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [12]:
ser.rank()

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

In [13]:
ser.rank(method='first')

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

In [14]:
ser.rank(ascending = False)

red       2.0
blue      5.0
yellow    4.0
white     1.0
green     3.0
dtype: float64

In [ ]:
 #Chapter 5 pandas: Reading and Writing Data